
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


test:
  stage: test

  parallel:
    matrix:
      - NODE_VERSION:
        - '10'
        - '12'
        - '14'
        - '15'

  image: node:${NODE_VERSION}-alpine

  before_script:
    - npm install

  script:
    - npm run test

  after_script:
    - npm run coverage

  artifacts:
    reports:
      cobertura: coverage/cobertura*.xml

  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

  rules:
    - if: '$NODE_VERSION == "15"'
      allow_failure: true


eslint:
  stage: test

  image: node:lts-alpine

  before_script:
    - npm install

  script:
    - npm run lint:ci

  artifacts:
    reports:
      junit: eslint.junit.xml
