
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml


.test:
  stage: test

  image: node:${NODE_VERSION}-alpine

  before_script:
    - npm install

  script:
    - npm run test

  after_script:
    - npm run coveralls

  artifacts:
    reports:
      cobertura: coverage/cobertura*.xml

  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/


test:node:10:
  extends:
    .test

  variables:
    NODE_VERSION: 10


test:node:12:
  extends:
    .test

  variables:
    NODE_VERSION: 12


test:node:14:
  extends:
    .test

  variables:
    NODE_VERSION: 14


eslint:
  stage: test

  image: node:lts-alpine

  before_script:
    - npm install

  script:
    - npm run lint:ci

  artifacts:
    reports:
      junit: eslint.junit.xml
